name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: the-coding-owl/action-typo3-extension-repository-upload@0.0.1
        env:
          SECRET_USERNAME: ${{ secrets.USERNAME }}
          SECRET_PASSWORD: ${{ secrets.PASSWORD }}
          EXTENSION_KEY: 'importr'
          UPLOAD_MESSAGE: 'Next release :) More information on https://github.com/sirdiego/importr/releases'
